### ISSUE TITLE
Question: Wanted some details

### ISSUE THREAD

**Issue by tomer-ds** [imoutsatsos/jenkins-scriptlets#3]
Hi Ioannis,

I found this repo during my research into building reports in Jenkins using Summary Display Plugin.
I found your mention of your script writeXMLproperties_scriptlet.groovy which looks like it could definitely help me out in my understanding and in general.

However it mentions other files that are not in the repo and to help get a fuller picture of what is required, I would very much like to see the file in question. 

The specific file referenced is online 21 of the script:
`reportConfigProps = configProps //scriptlet parameter:http://yourJenkinsUrl/userContent/reportConfiguration.properties`

Would it be at all possible to view this file?

**Comment by imoutsatsos** [comment]
Hi Tomer;
Have you reviewed the blog post here: http://biouno.org/2014/07/07/Consistent-Reports-for-Data-Analysis and the example properties configuration file here: https://github.com/imoutsatsos/jenkins-scriptlets/wiki/Summary-Display:-Report-Configuration-Properties ? They both have examples of a reportConfiguration.properties file. The file of course will be specific to your needs and the availability of output from your build that will drive the generation of the report. After revewing these please, let me know if you have any further questions. I'll be happy to send you more info. 

Best regards
Ioannis

**Comment by tomer-ds** [comment]
Hey Ioannis,
Thanks a ton for the direction! 
Looks like that will answer my questions.
I will be in touch if I have more.

Again, many thanks!

**Comment by tomer-ds** [comment]
Hi Ioannis,
I followed the blog and the info on the reference page.
I have managed to generate an XML although it looks like it is missing some data.
More over the Summary Report does not actually appear on the project or Results page (I have selected the option to view on both)

I have attached some basic test CSV's generated by my build, the proeties files for configProps, and the xml resulting from the scriplet.

[SummaryReport.zip](https://github.com/imoutsatsos/jenkins-scriptlets/files/3497094/SummaryReport.zip)
[SummaryReport-CSVs.zip](https://github.com/imoutsatsos/jenkins-scriptlets/files/3497083/SummaryReport-CSVs.zip)

The image is what I see... just the title of the results with no content

![SummaryReport](https://user-images.githubusercontent.com/30149311/62945469-733d4100-bde7-11e9-9d74-ae2105e70566.png)

Any ideas what I might be doing wrong?

**Comment by imoutsatsos** [comment]
Hi Tomer;
Thanks for attaching the files and especially the generated XML. I have a little project for just testing these. So here is what I was able to generated from your generated XML file. (concatenating the 3 tabs for easier viewing) 
![image](https://user-images.githubusercontent.com/3408226/62957142-3579f180-bdc2-11e9-830c-b35143aff3d6.png)

I think you are almost there! I'm suspecting that you are missing some post build actions. Insure that your project includes these two post-build actions
![image](https://user-images.githubusercontent.com/3408226/62957351-9d303c80-bdc2-11e9-8939-eb29920a72aa.png)

Let me know how it works for you.

Best regards
Ioannis

**Comment by imoutsatsos** [comment]
Issue reporter has no more comments. Assuming the provided solution fixed issue. Feel free to re-open if issue still exists.
